### ISSUE TITLE
migration to null safety? 

### ISSUE THREAD

**Issue by kaarens93** [ButterCMS/buttercms-dart#3]
package isn't compatible with newest flutter version

**Comment by jakelumetta** [comment]
Hi @kaarens93 - could you share more details around the error you're running into?

**Comment by mojomaze** [comment]
@jakelumetta the issue is the current package does not support null safety, which was introduced in Flutter 2.0. It's important that all direct dependencies support null safety in order for the app to run with sound null safety.

https://dart.dev/null-safety/migration-guide

**Comment by prasadsunny1** [comment]
I have sent a PR to migrate to null safety, waiting for @deven98's or @jakelumetta's reviews on it

**Comment by prasadsunny1** [comment]
Yay
