### ISSUE TITLE
Question: is this working for flutter mobile?

### ISSUE THREAD

**Issue by charlesc-ai** [ButterCMS/buttercms-dart#5]
Hello! I have a question for this library, is this working for flutter mobile or it's just working for Flutter Web version?

For mobile, how it can adapt to screen with such json?
```
"testimonial":  "<p>We've been able to make anvils faster than ever before! - <em>Chief Anvil Maker</em></p>\r\n<p><img src=\"https://cdn.buttercms.com/NiA3IIP3Ssurz5eNJ15a\" alt=\"\" caption=\"false\" width=\"249\" height=\"249\" /></p>"
```

Thank you!

**Comment by jakelumetta** [comment]
Hi @charlesc-ai - this package is a lightweight wrapper around the ButterCMS rest API:  https://buttercms.com/docs/api/

Butter supports many different field types:  https://buttercms.com/kb/content-fields

The one you're referring to is the WYSIWYG field type which provides editors a friendly UI and behind-the-scenes generates HTML output which is what our API then returns.

If you'd prefer not to have HTML for your mobile views, you can definitely do that. If you have any other technical questions, feel free to chat with us directly on our site. 👍
