### ISSUE TITLE
Search is not working well.

### ISSUE THREAD

**Issue by wupmemo** [ButterCMS/buttercms-dart#6]
When using the search functionality we are not getting the correct results. please see results here 
![Search-keywords](https://user-images.githubusercontent.com/15247512/124597482-24469c00-de96-11eb-9546-751d3af5f114.png)

Now the problem is that we are getting no results taking into account that the keywords are on those articles and in the keywords as well on ButterCMS.!! Please try to reach me on mohd.fouad@healthventure.com as this dependency is a core dependency on our ongoing startup.

**Comment by jakelumetta** [comment]
Thanks for the note. Our support team will be in touch to help troubleshoot.
